# Generated by Django 4.0.6 on 2022-07-21 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', models.CharField(max_length=1000, verbose_name='Content')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Published At')),
                ('state', models.IntegerField(choices=[(1, 'Draft '), (2, 'Published'), (3, 'Archived')], verbose_name='State')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
